=== berci/BerciRepo123/properties-from-xml/xsd/equipments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.camline.com/prop/1.0"
	targetNamespace="http://www.camline.com/prop/1.0">
	
	<xs:element name="equipmentConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipment" type="equipmentType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="equipmentType">
		<xs:sequence>
			<xs:element name="param" type="paramType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>	
	</xs:complexType>
	
	<xs:complexType name="paramType">
		<xs:attribute name="key" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="unit" type="xs:string" use="required"/>	
	</xs:complexType>
	
</xs:schema>

=== berci/BerciRepo123/properties-from-xml/xml/equipmentConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:equipmentConfig xmlns:p="http://www.camline.com/prop/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.camline.com/prop/1.0 equipments.xsd ">
	
	<equipment id="36543" name="STS Multiplex HP (Al-Kammer)">
		<param key="[1]" name="Ar" unit="sccm" />
		<param key="[2]" name="CF4" unit="sccm" />
		<param key="[3]" name="O2" unit="sccm" />
		<param key="[4]" name="CL2" unit="sccm" />
		<param key="[5]" name="HBr" unit="sccm" />
		<param key="[6]" name="SF6" unit="sccm" />
		<param key="[7]" name="C4F8" unit="sccm" />
	</equipment>
	<equipment id="20643" name="STS Multiplex ICP (Si-Kammer)">
		<param key="[1]" name="C4F8" unit="sccm" />
		<param key="[2]" name="SF6" unit="sccm" />
		<param key="[3]" name="O2" unit="sccm" />
		<param key="[4]" name="CF4" unit="sccm" />
	</equipment>
		
</p:equipmentConfig>
